### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ryotasykt** [ryotasykt/furima-29322#9]
#自身のフリマアプリのURL
https://furima-29322.herokuapp.com/

#Basic認証のIDとパスワード
ID：furima
パスワード：29322

#出品者用のメールアドレスとパスワード
メールアドレス：y@y
パスワード：123456a

#購入者用のメールアドレスとパスワード
メールアドレス：z@z
パスワード：123456a

#購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：3月23年
セキュリティコード：123

**Comment by kaho0919** [comment]
最終課題提出ありがとうございます。
一点のみ、修正・確認お願いいたします。

①Herokuでデプロイされているため、画像が消えています。
＜「S３設定」のお願い＞
「Heroku上で投稿した画像をS3へ保存する方法を学ぼう」という追加実装カリキュラムを取り組みましょう。
理由としては、Heroku上で扱う画像ファイルは、アプリがデプロイされるか、もしくはアプリが再起動（24時間に1回自動で行われる）される度に消えてしまうからです。
「提出したフリマアプリの画像が表示されていない」ということは好ましく無いため、こちらの設定をお願いします。
※設定方法はカリキュラムにありますので参照ください。
https://master.tech-camp.in/curriculums/4940

S3設定をされている場合は、今見えていない画像を見えるよう変えていただきたいです。
（画像が見えない等があると企業さまによっては、メンテナンスされてないとみられてしまうことがあるためです。）

上記設定しましたら、再度フォームにて提出をお願いします。

**Comment by Toshi0917** [comment]
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by ryotasykt** [comment]
ご確認いただきありがとうございます！
追加機能につきましては、自身で確認をさせていただきます。
